version: '2.0'
services:
  postgres:
    image: postgres:10-alpine
    container_name: db.social.network.io
    restart: always
    ports:
      - 5435:5432
    volumes:
      - ./docker/data/postgresql:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_USER: olesya
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: social_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8095:8080
